### ISSUE TITLE
Removing files on jniLibs.

### ISSUE THREAD

**Issue by rhonyabdullah** [r4ghu/OpenCVAndroid-AnIntroduction#2]
I was read your blogpost [here](https://sriraghu.com/2017/03/11/opencv-in-android-an-introduction-part-1/) onething, why we need to remove another files except this **libopencv_java3.so** on jniLibs folder ?

**Comment by r4ghu** [comment]
Please check this [thread](https://stackoverflow.com/questions/9809213/what-are-a-and-so-files) on Stack-overflow for more details.
